on:
    pull_request_target:
        types: [opened]
    push:
name: Pull request automation

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    pull-request-automation:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
            pull-requests: write
        if: ${{ github.repository == 'yashjawale/gutenberg' }}

        steps:
            # Checkout defaults to using the branch which triggered the event, which
            # isn't necessarily `trunk` (e.g. in the case of a merge).
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: trunk
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - name: Verify file structure
              run: ls -R

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Build project management automation package
              run: |
                  shopt -s globstar
                  files=(packages/project-management-automation/src/**/*.ts)

                  # Only run the build if files were found
                  if [ -e "${files[0]}" ]; then
                  echo "Found ${#files[@]} files to build."
                  node bin/packages/build.js "${files[@]}"
                  else
                  echo "No TypeScript files found to build. Skipping."
                  fi
              shell: bash

            - uses: ./packages/project-management-automation
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
